package com.revxrsal.betterspender.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF215fa6)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFd3e3ff)
val light_onPrimaryContainer = Color(0xFF001b3c)
val light_secondary = Color(0xFF555f71)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd9e3f8)
val light_onSecondaryContainer = Color(0xFF121c2b)
val light_tertiary = Color(0xFF6e5676)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFf7d8fe)
val light_onTertiaryContainer = Color(0xFF27132f)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfdfbff)
val light_onBackground = Color(0xFF1b1b1d)
val light_surface = Color(0xFFfdfbff)
val light_onSurface = Color(0xFF1b1b1d)
val light_surfaceVariant = Color(0xFFe0e2eb)
val light_onSurfaceVariant = Color(0xFF43474e)
val light_outline = Color(0xFF74777f)
val light_inverseOnSurface = Color(0xFFf1f0f4)
val light_inverseSurface = Color(0xFF2f3033)
val light_inversePrimary = Color(0xFFa4c8ff)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFFa4c8ff)
val dark_onPrimary = Color(0xFF003061)
val dark_primaryContainer = Color(0xFF004689)
val dark_onPrimaryContainer = Color(0xFFd3e3ff)
val dark_secondary = Color(0xFFbcc7dc)
val dark_onSecondary = Color(0xFF273141)
val dark_secondaryContainer = Color(0xFF3d4758)
val dark_onSecondaryContainer = Color(0xFFd9e3f8)
val dark_tertiary = Color(0xFFdbbde2)
val dark_onTertiary = Color(0xFF3e2846)
val dark_tertiaryContainer = Color(0xFF553e5d)
val dark_onTertiaryContainer = Color(0xFFf7d8fe)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1b1b1d)
val dark_onBackground = Color(0xFFe3e2e6)
val dark_surface = Color(0xFF1b1b1d)
val dark_onSurface = Color(0xFFe3e2e6)
val dark_surfaceVariant = Color(0xFF43474e)
val dark_onSurfaceVariant = Color(0xFFc3c6cf)
val dark_outline = Color(0xFF8e9199)
val dark_inverseOnSurface = Color(0xFF1b1b1d)
val dark_inverseSurface = Color(0xFFe3e2e6)
val dark_inversePrimary = Color(0xFF215fa6)
val dark_shadow = Color(0xFF000000)



val seed = Color(0xFF3764a0)
val error = Color(0xFFba1b1b)